id = "umbralkai"
name = "Umbralkai"
version = "0.1.0"
schema_version = 1
authors = ["Andrew Sen <platformer@github.com>"]
description = "A dark theme with perceptually uniform syntax colors. Inspired by Monokai and Penumbra."
repository = "https://github.com/platformer/zed-umbralkai"
